version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo installing dependencies...
      - cd expense-manager-ui/ && npm install && npm install -g @angular/cli
  build:
    commands:
      - cd expense-manager-ui/ && ng build --production
artifacts:
  files:
    - "**/*"
  base-directory: 'dist*'
  discard-paths: yes