version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo installing dependencies...
      - pwd
      - cd expense-manager-ui/ 
      - pwd
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo attempting to build
      - pwd
      - ng build --prod
artifacts:
  files:
    - "**/*"
  base-directory: 'dist*'
  discard-paths: yes